---
- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Install common dependencies
  yum: name={{ item }} state=installed
  with_items:
   - libselinux-python
   - libsemanage-python
   - firewalld
- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp
- name: Disable the firewalld  service
  service: name=firewalld state=stopped enabled=no
  tags: firewall
- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp
